# Generated by Django 6.0.3 on 2026-04-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkprofiling_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kkaddress',
            name='purok',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
