# Generated by Django 6.0.3 on 2026-04-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkprofiling_api', '0002_kkaddress_purok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkaddress',
            name='kk_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='kkprofiling_api.profilinginformations'),
        ),
        migrations.AlterField(
            model_name='youthstatus',
            name='kk_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youth_statuses', to='kkprofiling_api.profilinginformations'),
        ),
    ]
