# Generated by Django 6.0.3 on 2026-05-21 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkprofiling_api', '0003_alter_kkaddress_kk_name_alter_youthstatus_kk_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkaddress',
            name='kk_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='kkprofiling_api.profilinginformations'),
        ),
    ]
