# Generated by Django 6.0.3 on 2026-04-10 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_rename_user_usermmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMModel',
            new_name='UserModel',
        ),
    ]
