# Generated by Django 6.0.3 on 2026-04-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_members_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sk_picture',
            field=models.ImageField(blank=True, null=True, upload_to='sk_pictures/'),
        ),
    ]
