# Generated by Django 6.0.3 on 2026-05-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_members_api', '0002_member_sk_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
