# Generated by Django 6.0.3 on 2026-05-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_members_api', '0003_member_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, choices=[('SK Chairperson', 'SK Chairperson'), ('SK Secretary', 'SK Secretary'), ('SK Treasurer', 'SK Treasurer'), ('SK Councilor 1', 'SK Councilor 1'), ('SK Councilor 2', 'SK Councilor 2'), ('SK Councilor 3', 'SK Councilor 3'), ('SK Councilor 4', 'SK Councilor 4'), ('SK Councilor 5', 'SK Councilor 5'), ('SK Councilor 6', 'SK Councilor 6'), ('SK Councilor 7', 'SK Councilor 7')], max_length=100, null=True),
        ),
    ]
